### ISSUE TITLE
Segfault in `generate` on Windows (test branch)

### ISSUE THREAD

**Issue by EionRobb** [vysheng/tgl#71]
I don't really know enough about how the generate code works to be able to debug or fix this one, but hopefully the backtrace helps

```
(gdb) run auto/scheme.tlo
Starting program: C:\cygwin\home\Eion\telegram-purple-dev-1.2.3\tgl\generate.exe auto/scheme.tlo
[New Thread 1404.0x2914]
[New Thread 1404.0x1468]
[New Thread 1404.0x1a8c]

Program received signal SIGSEGV, Segmentation fault.
0x00401614 in new_tree_node_tl_type (x=0xd71a68, y=41) at generate.c:79
79      DEFINE_TREE (tl_type, struct tl_type *, tl_type_name_cmp, 0)
(gdb) bt full
#0  0x00401614 in new_tree_node_tl_type (x=0xd71a68, y=41) at generate.c:79
        T = 0x773f2bfe <ntdll!RtlAllocateHeap+46>
#1  0x0040174e in tree_insert_tl_type (T=0x0, x=0xd71a68, y=41) at generate.c:79
No locals.
#2  0x0040237b in tl_type_insert_by_name (t=0xd71a68) at generate.c:97
No locals.
#3  0x0040a505 in read_types () at generate.c:2281
        t = 0xd71a68
#4  0x0040cf9d in parse_tlo_file () at generate.c:2855
        i = 0
        j = 7798732
#5  0x0040d87e in main (argc=2, argv=0xd71670) at generate.c:3026
        i = -1
        fd = 3
(gdb)
```

**Comment by BenWiederhake** [comment]
Can be closed due to #78
